// Votes
export const CREATE_VOTE_REQUEST = 'CREATE_VOTE_REQUEST'
export const CREATE_VOTE_SUCCESS = 'CREATE_VOTE_SUCCESS' 
export const CREATE_VOTE_FAILURE = 'CREATE_VOTE_FAILURE'

export const DELETE_VOTE_REQUEST = 'DELETE_VOTE_REQUEST'
export const DELETE_VOTE_SUCCESS = 'DELETE_VOTE_SUCCESS'
export const DELETE_VOTE_FAILURE = 'DELETE_VOTE_FAILURE'

// Comments
export const COMMENTS_REQUEST = 'COMMENTS_REQUEST'
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS'
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE'

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE'

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE'

export const CLEAR_COMMENTS = 'CLEAR_COMMENTS'

export const UPDATE_COMMENT_FORM_COUNTER = 'UPDATE_COMMENT_FORM_COUNTER'

// Users
export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FAILURE = 'USER_FAILURE'

// Relationships
export const CREATE_RELATIONSHIP_REQUEST = 'CREATE_RELATIONSHIP_REQUEST'
export const CREATE_RELATIONSHIP_SUCCESS = 'CREATE_RELATIONSHIP_SUCCESS'
export const CREATE_RELATIONSHIP_FAILURE = 'CREATE_RELATIONSHIP_FAILURE'

export const DELETE_RELATIONSHIP_REQUEST = 'DELETE_RELATIONSHIP_REQUEST'
export const DELETE_RELATIONSHIP_SUCCESS = 'DELETE_RELATIONSHIP_SUCCESS'
export const DELETE_RELATIONSHIP_FAILURE = 'DELETE_RELATIONSHIP_FAILURE'

// Posts
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const INVALIDATE_CATEGORY_POSTS = 'INVALIDATE_CATEGORY_POSTS'

// Notifications
export const NOTIFICATIONS_REQUEST = 'NOTIFICATIONS_REQUEST'
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS'
export const NOTIFICATIONS_FAILURE = 'NOTIFICATIONS_FAILURE'

// Log in/Log out
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

// Errors
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

// Modals
export const TOGGLE_MODAL = 'TOGGLE_MODAL'

// Current gallery
export const UPDATE_CURRENT_GALLERY = 'UPDATE_CURRENT_GALLERY'